name: unit-tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker compose up
        run: docker-compose up -d
      - name: Run unit tests
        run: docker exec irc_irc_1 /bin/bash -c "mkdir build && cd build && cmake .. && make && ctest"
      - name: Docker compose down
        run: docker-compose down
